### ISSUE TITLE
Plugin Crashes when creating cross-server portal

### ISSUE THREAD

**Issue by patritha** [Lauriethefish/BetterPortals#173] opened 2022-10-11 22:17 UTC
**Describe the bug**
I tried to make a cross server portal and the plugin crashes

**To Reproduce**
go to survival server
make a destination portal
go to lobby
make an origin portal
run /bp linkexternal
watch it crash and burn

**Server Logs**
```[17:03:27 INFO]: TrumpetsRlife issued server command: /bp linkexternal
[17:03:28 ERROR]: [BetterPortals] A critical error occurred during plugin execution.
[17:03:28 ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[17:03:28 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.data.BlockData.getMaterial()" because "destData" is null
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.block.bukkit.BukkitBlockMap.searchFromBlock(BukkitBlockMap.java:106)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.block.FloodFillBlockMap.updateInternal(FloodFillBlockMap.java:113)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.block.bukkit.BukkitBlockMap.updateInternal(BukkitBlockMap.java:314)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.block.FloodFillBlockMap.update(FloodFillBlockMap.java:102)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.portal.Portal.onViewUpdate(Portal.java:88)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.portal.PortalActivityManager.onPortalViewedThisTick(PortalActivityManager.java:51)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:77)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
[17:03:28 WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[17:03:28 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[17:03:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:03:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1518)
[17:03:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1442)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1209)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
[17:03:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:03:28 INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[17:03:28 INFO]: [BetterPortals] Disabling BetterPortals v0.12.1
[17:03:28 INFO]: [BetterPortals] Disconnecting from the proxy
[17:03:28 WARN]: [BetterPortals] Failed to fetch block changes for external portal:
[17:03:28 WARN]: com.lauriethefish.betterportals.shared.net.RequestException: Disconnected from proxy while sending the request
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.net.PortalClient.disconnect(PortalClient.java:257)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.net.PortalClient.shutDown(PortalClient.java:211)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.BetterPortals.onDisable(BetterPortals.java:167)
[17:03:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[17:03:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
[17:03:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.shutdownPlugin(CrashHandler.java:28)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.processCriticalError(CrashHandler.java:23)
[17:03:28 WARN]:        at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:62)
[17:03:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:03:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1518)
[17:03:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:485)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1442)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1209)
[17:03:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
[17:03:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:04:07 INFO]: TrumpetsRlife issued server command: /bp reconnect
[17:04:07 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'bp' in plugin BetterPortals v0.12.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2474) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2245) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[purpur-1.19.jar:git-Purpur-1735]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:04:24 INFO]: TrumpetsRlife issued server command: /plugins```



**Additional context**
Plugin Version: 0.12.1
Game Version: 1.19 (purpur-1.19-1735)

**Comment by Lauriethefish** [comment] 2022-10-12 06:08
Closing as duplicate of #148

**Closed as completed by Lauriethefish** 2022-10-12 06:08 UTC
Labels: bug
