### ISSUE TITLE
Portals joining

### ISSUE THREAD

**Issue by ErythroCraft** [Lauriethefish/BetterPortals#10] opened 2021-01-28 20:52 UTC
Hi

The second issue is very complicatated.

If player are running, jumping or sneaking by the portals there seeing an black wall.

Watch out the picture.

![unknown](https://user-images.githubusercontent.com/76217862/106197516-1d16b600-61b3-11eb-9a7b-e7719ace7dea.png)

**Comment by Lauriethefish** [comment] 2021-01-28 20:53
Huh, very strange issue. Does a relog fix it temporarily?

**Comment by Lauriethefish** [comment] 2021-01-28 21:01
Enable debug logging please, this will give me more info about the saving issue.

**Comment by ErythroCraft** [comment] 2021-01-28 21:17
It is self as

https://github.com/Lauriethefish/BetterPortals/issues/9#issuecomment-769400661

**Comment by ErythroCraft** [comment] 2021-01-28 21:42
vid created by friend non listed

https://www.youtube.com/watch?v=U-3nO1uZID8&ab_channel=LumenSol

**Comment by Lauriethefish** [comment] 2021-01-29 05:52
I think I might see the cause of the issue.
It appears to be portal background blocks not resetting correctly.

For a temporary fix, you'll want to create portals that aren't as close to each other as this.
For a permanent fix, the next version should have a patch for this.
I'm doing a rewrite however, so it will be a while.

**Comment by ErythroCraft** [comment] 2021-01-29 10:39
Yes, thank you very much for that.

However, I prefer to wait. 
The server will only go to the start with version 1.17 anyway.

We also have a lot to do, too.

**Comment by Lauriethefish** [comment] 2021-01-29 12:17
Due to my inability to reproduce this issue, I'm going to have to close it.

**Closed by Lauriethefish** 2021-01-29 12:17 UTC
