### ISSUE TITLE
Exception when throwing item through end portal

### ISSUE THREAD

**Issue by Teals53** [Lauriethefish/BetterPortals#38] opened 2021-04-24 21:44 UTC
try to put some item in end portal and take this error

```[21:43:15 ERROR]: Could not pass event PortalCreateEvent to BetterPortals v0.8.0
java.lang.IllegalStateException: Invalid PortalCreateEvent called by Bukkit. Portal was not on a valid plane
        at com.lauriethefish.betterportals.bukkit.events.SpawningEvents.findPortalDirection(SpawningEvents.java:150) ~[?:?]
        at com.lauriethefish.betterportals.bukkit.events.SpawningEvents.onPortalCreate(SpawningEvents.java:90) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor183.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-625]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-625]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-625]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:2411) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.Entity.teleportTo(Entity.java:2700) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.Entity.b(Entity.java:2655) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.EntityItem.b(EntityItem.java:467) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.BlockEnderPortal.a(BlockEnderPortal.java:63) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:626) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.Entity.checkBlockCollisions(Entity.java:1070) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:805) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.EntityItem.tick(EntityItem.java:120) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1486) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-625]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-625]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by Lauriethefish** [comment] 2021-04-25 05:16
Unavailable atm, will look into this soon.

**Comment by Teals53** [comment] 2021-04-25 10:50
F

**Comment by Lauriethefish** [comment] 2021-05-14 05:21
I need your server version - I can't reproduce this issue on 1.16.5

**Comment by Teals53** [comment] 2021-05-14 09:35
its latest so 1.16.5

**Comment by Lauriethefish** [comment] 2021-07-25 12:51
Can't reproduce this issue, so I'm going to close it for now. If somebody knows a reliable way to reproduce this, comment and I'll open it back up.

**Closed by Lauriethefish** 2021-07-25 12:51 UTC
Labels: bug
