### ISSUE TITLE
NullPointerException in console (no further information as of yet)

### ISSUE THREAD

**Issue by Dexter4002** [Lauriethefish/BetterPortals#7] opened 2020-11-04 10:03 UTC
[09:53:50 WARN]: [BetterPortals] Task #243380 for BetterPortals v0.59 generated an exception
java.lang.NullPointerException: null
        at com.lauriethefish.betterportals.runnables.MainUpdate.updateEntities(MainUpdate.java:112) ~[?:?]
        at com.lauriethefish.betterportals.runnables.MainUpdate.run(MainUpdate.java:171) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by Lauriethefish** [comment] 2020-11-04 10:44
Could I have some more information?
- When did this error occur?
- Does it spam the console, or just happen once?
- What other plugins do you have installed?
- What is your server version (e.g. Spigot 1.13.2)

**Comment by Lauriethefish** [comment] 2020-11-08 20:42
As far as I know this is caused by a memory issue with pterodactyl. Closing for now.
(this was after further discussion on discord).

**Closed by Lauriethefish** 2020-11-08 20:42 UTC
Labels: bug
