### ISSUE TITLE
Plugin random crash (mostly when stuff an entity through portal)

### ISSUE THREAD

**Issue by oli1505** [Lauriethefish/BetterPortals#114] opened 2021-12-31 16:41 UTC
**Describe the bug**
The first time it happend in front of me. A piglin walked through the portal and the plugin was gone. This was on version 0.10.1
I restarted the server and tried pushing piglins and other enteties through and nothing happend. I saw that theres a newer version availalbe and installed it. I activatet the FINER log and kept watching. Today we tried pushing a villager in a minecart through the portal and it crashed again.

The mobs which went through the portal without crashing got into the void. They were all gone no drops or anything. The config file is  on default.

**To Reproduce**
Idk

**Server Logs**
[log-cut.log](https://github.com/Lauriethefish/BetterPortals/files/7796646/log-cut.log)

**Additional context**
Plugin Version: 0.10.2 and 0.10.1
Game Version: Spigot 1.18

**Comment by oli1505** [comment] 2022-01-09 18:37
The plugin ran almost 6 days without a crash. I'm not sure if the people were active the days.


[19:20:44] [Server thread/INFO]: [BetterPortals] [FNE] Viewable block array update took: 7,124 ms. Block count: 7638. Viewable count: 4624
[19:20:45] [Server thread/INFO]: [BetterPortals] [FNE] Viewable block array update took: 2,051 ms. Block count: 7638. Viewable count: 4624
[19:20:45] [BetterPortals View Update Thread/INFO]: [BetterPortals] [FST] Refreshing already sent blocks!
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNE] Teleporting entity with ID 151815 and of type BAT to position 108.53472149647973,79.19013514024464,2.544398811323788
[19:20:46] [Server thread/ERROR]: [BetterPortals] A critical error occurred during plugin execution.
[19:20:46] [Server thread/ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[19:20:46] [Server thread/WARN]: java.util.ConcurrentModificationException
[19:20:46] [Server thread/WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[19:20:46] [Server thread/WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[19:20:46] [Server thread/WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.PortalEntityManager.handleTeleportation(PortalEntityManager.java:93)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.PortalEntityManager.update(PortalEntityManager.java:71)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.portal.Portal.onUpdate(Portal.java:81)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.portal.PortalActivityManager.onPortalActivatedThisTick(PortalActivityManager.java:36)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.updateViewablePortals(PlayerData.java:92)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:108)
[19:20:46] [Server thread/WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[19:20:46] [Server thread/WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[19:20:46] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[19:20:46] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[19:20:46] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[19:20:46] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255)
[19:20:46] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428)
[19:20:46] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206)
[19:20:46] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034)
[19:20:46] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[19:20:46] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:20:46] [Server thread/INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[19:20:46] [Server thread/INFO]: [BetterPortals] Disabling BetterPortals v0.10.2
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNR] Checking deactivation type of portal view, previous pos: (833,96, -49,00, 29,18, world), current pos: (833,96, -49,00, 29,18, world)
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNR] Player block view deactivating. Should reset states: true
[19:20:46] [Server thread/INFO]: [BetterPortals] [FST] Resetting immediately!
[19:20:46] [Server thread/INFO]: [BetterPortals] [FST] Resetting 77 blocks
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNE] Saving all portals . . .
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNE] Saved 14 portals
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNE] Saving to plugins/BetterPortals/data/portals.yml
[19:20:46] [BetterPortals View Update Thread/INFO]: [BetterPortals] [FNE] Goodbye from block view update thread!
[19:20:46] [Server thread/INFO]: [BetterPortals] [FNE] Goodbye!

**Comment by Lauriethefish** [comment] 2022-07-10 14:46
Closing since I'm pretty sure this is fixed. If it is reproduced again please let me know.

**Closed by Lauriethefish** 2022-07-10 14:46 UTC
Labels: bug
